'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Database
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SalesInvoice.Database", GetType(Database).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ALTER TABLE [categories] ADD PRIMARY KEY ([id]); ALTER TABLE [clients] ADD PRIMARY KEY ([id]); ALTER TABLE [items] ADD PRIMARY KEY ([id]); ALTER TABLE [receipts] ADD PRIMARY KEY ([id]); ALTER TABLE [receiptsdetails] ADD  PRIMARY KEY ([id]); ALTER TABLE [units] ADD PRIMARY KEY ([id]); CREATE UNIQUE INDEX [UQ__categories] ON [categories] ([id] ASC); CREATE UNIQUE INDEX [UQ__clients] ON [clients] ([id] ASC); CREATE UNIQUE INDEX [UQ__receipts] ON [receipts] ([id] ASC); CREATE UNIQUE INDEX [UQ__receipts_data] ON [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property table_alters() As String
            Get
                Return ResourceManager.GetString("table_alters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE [categories] ( [id] int NOT NULL  IDENTITY (1,1),[name] nvarchar(100) NULL);.
        '''</summary>
        Friend Shared ReadOnly Property tableCategories() As String
            Get
                Return ResourceManager.GetString("tableCategories", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO categories(name) VALUES (&apos;Uncategorized&apos;);.
        '''</summary>
        Friend Shared ReadOnly Property tableCategories_data() As String
            Get
                Return ResourceManager.GetString("tableCategories_data", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE [clients] ([id] int NOT NULL  IDENTITY (1,1), [name] nvarchar(100) NOT NULL, [phone] nvarchar(15) NULL, [address] nvarchar(200) NULL, [identificator] nvarchar(15) NULL);.
        '''</summary>
        Friend Shared ReadOnly Property tableClients() As String
            Get
                Return ResourceManager.GetString("tableClients", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE [config] ([Id] int IDENTITY (1,1) NOT NULL, [config_key] nvarchar(100) NOT NULL, [config_value] nvarchar(100) NULL);.
        '''</summary>
        Friend Shared ReadOnly Property tableConfig() As String
            Get
                Return ResourceManager.GetString("tableConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO [config](config_key,config_value)  VALUES (&apos;sellerName&apos;,NULL);
        '''INSERT INTO [config](config_key,config_value)  VALUES (&apos;sellerAddress&apos;,NULL);
        '''INSERT INTO [config](config_key,config_value)  VALUES (&apos;sellerHeader&apos;,NULL);
        '''INSERT INTO [config](config_key,config_value)  VALUES (&apos;sellerFooter&apos;,NULL);
        '''INSERT INTO [config](config_key,config_value)  VALUES (&apos;sellerAccountNo&apos;,NULL);
        '''INSERT INTO [config](config_key,config_value)  VALUES (&apos;sellerBankInfo&apos;,NULL);
        '''INSERT INTO [config](config_key,config_v [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property tableConfig_data() As String
            Get
                Return ResourceManager.GetString("tableConfig_data", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE [items] ([id] int NOT NULL  IDENTITY (1,1), [name] nvarchar(100) NULL, [category] int NULL, [unit] int NULL, [price] float NULL);.
        '''</summary>
        Friend Shared ReadOnly Property tableItems() As String
            Get
                Return ResourceManager.GetString("tableItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE [receipts] ([id] int NOT NULL  IDENTITY (1,1), [receipt_id] nvarchar(30) NOT NULL, [client_id] int NULL, [ddate] datetime NULL);.
        '''</summary>
        Friend Shared ReadOnly Property tableReceipts() As String
            Get
                Return ResourceManager.GetString("tableReceipts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE [receiptsdetails] ([receipt_id] nvarchar(30) NULL, [amount] float NULL, [code] int NULL, [id] int NOT NULL  IDENTITY (1,1));.
        '''</summary>
        Friend Shared ReadOnly Property tableReceiptsDetails() As String
            Get
                Return ResourceManager.GetString("tableReceiptsDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to CREATE TABLE [units] ([id] int NOT NULL  IDENTITY (1,1), [name] nvarchar(10) NULL);.
        '''</summary>
        Friend Shared ReadOnly Property tableUnits() As String
            Get
                Return ResourceManager.GetString("tableUnits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to INSERT INTO units(name) VALUES (&apos;szt.&apos;);
        '''INSERT INTO units(name) VALUES(&apos;m&apos;);
        '''INSERT INTO units(name) VALUES(&apos;kg&apos;);
        '''INSERT INTO units(name) VALUES(&apos;l&apos;);.
        '''</summary>
        Friend Shared ReadOnly Property tableUnits_data() As String
            Get
                Return ResourceManager.GetString("tableUnits_data", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
