'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Language_pl
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SalesInvoice.Language_pl", GetType(Language_pl).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Numer konta.
        '''</summary>
        Friend Shared ReadOnly Property lbAccountNO() As String
            Get
                Return ResourceManager.GetString("lbAccountNO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dodaj.
        '''</summary>
        Friend Shared ReadOnly Property lbAdd() As String
            Get
                Return ResourceManager.GetString("lbAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dodaj kategorię.
        '''</summary>
        Friend Shared ReadOnly Property lbAddCategory() As String
            Get
                Return ResourceManager.GetString("lbAddCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dodaj klienta.
        '''</summary>
        Friend Shared ReadOnly Property lbAddClient() As String
            Get
                Return ResourceManager.GetString("lbAddClient", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dodaj towar.
        '''</summary>
        Friend Shared ReadOnly Property lbAddItem() As String
            Get
                Return ResourceManager.GetString("lbAddItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Adres.
        '''</summary>
        Friend Shared ReadOnly Property lbAddress() As String
            Get
                Return ResourceManager.GetString("lbAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Numer budynku.
        '''</summary>
        Friend Shared ReadOnly Property lbAddressNo() As String
            Get
                Return ResourceManager.GetString("lbAddressNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dodaj jednostki.
        '''</summary>
        Friend Shared ReadOnly Property lbAddUnits() As String
            Get
                Return ResourceManager.GetString("lbAddUnits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ilość.
        '''</summary>
        Friend Shared ReadOnly Property lbAmount() As String
            Get
                Return ResourceManager.GetString("lbAmount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zatwierdź.
        '''</summary>
        Friend Shared ReadOnly Property lbApply() As String
            Get
                Return ResourceManager.GetString("lbApply", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Na pewno?.
        '''</summary>
        Friend Shared ReadOnly Property lbAreYouSure() As String
            Get
                Return ResourceManager.GetString("lbAreYouSure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wstecz.
        '''</summary>
        Friend Shared ReadOnly Property lbBack() As String
            Get
                Return ResourceManager.GetString("lbBack", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dane banku.
        '''</summary>
        Friend Shared ReadOnly Property lbBankAddress() As String
            Get
                Return ResourceManager.GetString("lbBankAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dane bankowe.
        '''</summary>
        Friend Shared ReadOnly Property lbBankDetails() As String
            Get
                Return ResourceManager.GetString("lbBankDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Informacje bankowe.
        '''</summary>
        Friend Shared ReadOnly Property lbBankInfo() As String
            Get
                Return ResourceManager.GetString("lbBankInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tutaj znajdują się informacje o koncie bankowym, jeśli 
        '''	przewidujesz opcję zapłaty przelewem bankowym, wypełnij te 
        '''	pola, w przeciwnym razie możliwość płatności przelewem będzie
        '''	zablokowana.
        '''
        '''Te ustawienia można później zmienić w Ustawieniach..
        '''</summary>
        Friend Shared ReadOnly Property lbBankInfoWizard() As String
            Get
                Return ResourceManager.GetString("lbBankInfoWizard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Przelew bankowy.
        '''</summary>
        Friend Shared ReadOnly Property lbBankTransfer() As String
            Get
                Return ResourceManager.GetString("lbBankTransfer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Anuluj.
        '''</summary>
        Friend Shared ReadOnly Property lbCancel() As String
            Get
                Return ResourceManager.GetString("lbCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nie można cofnąć tej operacji..
        '''</summary>
        Friend Shared ReadOnly Property lbCannotUndone() As String
            Get
                Return ResourceManager.GetString("lbCannotUndone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Gotówka.
        '''</summary>
        Friend Shared ReadOnly Property lbCash() As String
            Get
                Return ResourceManager.GetString("lbCash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kategorie towarów:.
        '''</summary>
        Friend Shared ReadOnly Property lbCategories() As String
            Get
                Return ResourceManager.GetString("lbCategories", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kategoria.
        '''</summary>
        Friend Shared ReadOnly Property lbCategory() As String
            Get
                Return ResourceManager.GetString("lbCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Środek.
        '''</summary>
        Friend Shared ReadOnly Property lbCenter() As String
            Get
                Return ResourceManager.GetString("lbCenter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wybierz.
        '''</summary>
        Friend Shared ReadOnly Property lbChoose() As String
            Get
                Return ResourceManager.GetString("lbChoose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wybierz szablon.
        '''</summary>
        Friend Shared ReadOnly Property lbChooseTemplate() As String
            Get
                Return ResourceManager.GetString("lbChooseTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Miejscowość.
        '''</summary>
        Friend Shared ReadOnly Property lbCity() As String
            Get
                Return ResourceManager.GetString("lbCity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Czyszczenie.
        '''</summary>
        Friend Shared ReadOnly Property lbCleaning() As String
            Get
                Return ResourceManager.GetString("lbCleaning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Klient.
        '''</summary>
        Friend Shared ReadOnly Property lbClient() As String
            Get
                Return ResourceManager.GetString("lbClient", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Szczegóły kontrahenta.
        '''</summary>
        Friend Shared ReadOnly Property lbClientDetails() As String
            Get
                Return ResourceManager.GetString("lbClientDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Klienci.
        '''</summary>
        Friend Shared ReadOnly Property lbClients() As String
            Get
                Return ResourceManager.GetString("lbClients", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zamknij.
        '''</summary>
        Friend Shared ReadOnly Property lbClose() As String
            Get
                Return ResourceManager.GetString("lbClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kod.
        '''</summary>
        Friend Shared ReadOnly Property lbCode() As String
            Get
                Return ResourceManager.GetString("lbCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wartość.
        '''</summary>
        Friend Shared ReadOnly Property lbCost() As String
            Get
                Return ResourceManager.GetString("lbCost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Utwórz.
        '''</summary>
        Friend Shared ReadOnly Property lbCreate() As String
            Get
                Return ResourceManager.GetString("lbCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Utwórz bazę.
        '''</summary>
        Friend Shared ReadOnly Property lbCreateDB() As String
            Get
                Return ResourceManager.GetString("lbCreateDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Utwórz zadanie.
        '''</summary>
        Friend Shared ReadOnly Property lbCreateTask() As String
            Get
                Return ResourceManager.GetString("lbCreateTask", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Baza.
        '''</summary>
        Friend Shared ReadOnly Property lbDatabase() As String
            Get
                Return ResourceManager.GetString("lbDatabase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pobierz dane z CEIDG.
        '''</summary>
        Friend Shared ReadOnly Property lbDataFromCEIDG() As String
            Get
                Return ResourceManager.GetString("lbDataFromCEIDG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data.
        '''</summary>
        Friend Shared ReadOnly Property lbDate() As String
            Get
                Return ResourceManager.GetString("lbDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Domyślny.
        '''</summary>
        Friend Shared ReadOnly Property lbDefault() As String
            Get
                Return ResourceManager.GetString("lbDefault", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usuń.
        '''</summary>
        Friend Shared ReadOnly Property lbDelete() As String
            Get
                Return ResourceManager.GetString("lbDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usuń bazę.
        '''</summary>
        Friend Shared ReadOnly Property lbDeleteDB() As String
            Get
                Return ResourceManager.GetString("lbDeleteDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Numer dokumentu.
        '''</summary>
        Friend Shared ReadOnly Property lbDocumentNo() As String
            Get
                Return ResourceManager.GetString("lbDocumentNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edytuj.
        '''</summary>
        Friend Shared ReadOnly Property lbEdit() As String
            Get
                Return ResourceManager.GetString("lbEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edytuj kategorie...
        '''</summary>
        Friend Shared ReadOnly Property lbEditCategories() As String
            Get
                Return ResourceManager.GetString("lbEditCategories", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edytuj kategorie towaru.
        '''</summary>
        Friend Shared ReadOnly Property lbEditCategory() As String
            Get
                Return ResourceManager.GetString("lbEditCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edytuj jednostki.
        '''</summary>
        Friend Shared ReadOnly Property lbEditUnits() As String
            Get
                Return ResourceManager.GetString("lbEditUnits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Włącz usługę skanera kodów.
        '''</summary>
        Friend Shared ReadOnly Property lbEnableScannerService() As String
            Get
                Return ResourceManager.GetString("lbEnableScannerService", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zakończ.
        '''</summary>
        Friend Shared ReadOnly Property lbEnd() As String
            Get
                Return ResourceManager.GetString("lbEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uzupełnij wymagane pola!.
        '''</summary>
        Friend Shared ReadOnly Property lbEnterAllData() As String
            Get
                Return ResourceManager.GetString("lbEnterAllData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wyjdź.
        '''</summary>
        Friend Shared ReadOnly Property lbExit() As String
            Get
                Return ResourceManager.GetString("lbExit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eksportuj.
        '''</summary>
        Friend Shared ReadOnly Property lbExport() As String
            Get
                Return ResourceManager.GetString("lbExport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Eksportuj bazę.
        '''</summary>
        Friend Shared ReadOnly Property lbExportDB() As String
            Get
                Return ResourceManager.GetString("lbExportDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dodatki.
        '''</summary>
        Friend Shared ReadOnly Property lbExtras() As String
            Get
                Return ResourceManager.GetString("lbExtras", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pierwsze uruchomienie.
        '''</summary>
        Friend Shared ReadOnly Property lbFisrtRun() As String
            Get
                Return ResourceManager.GetString("lbFisrtRun", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stopka.
        '''</summary>
        Friend Shared ReadOnly Property lbFooterText() As String
            Get
                Return ResourceManager.GetString("lbFooterText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generuj.
        '''</summary>
        Friend Shared ReadOnly Property lbGenerate() As String
            Get
                Return ResourceManager.GetString("lbGenerate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generowanie....
        '''</summary>
        Friend Shared ReadOnly Property lbGenerating() As String
            Get
                Return ResourceManager.GetString("lbGenerating", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tekst nagłówka.
        '''</summary>
        Friend Shared ReadOnly Property lbHeaderText() As String
            Get
                Return ResourceManager.GetString("lbHeaderText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dane nagłówka i stopki.
        '''</summary>
        Friend Shared ReadOnly Property lbHeadInfo() As String
            Get
                Return ResourceManager.GetString("lbHeadInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Informacje nagłówka 
        '''(będą umieszczone w lewym górnym rogu rachunku).
        '''</summary>
        Friend Shared ReadOnly Property lbHeadInfoWizard() As String
            Get
                Return ResourceManager.GetString("lbHeadInfoWizard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cześć!.
        '''</summary>
        Friend Shared ReadOnly Property lbHi() As String
            Get
                Return ResourceManager.GetString("lbHi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ID.
        '''</summary>
        Friend Shared ReadOnly Property lbID() As String
            Get
                Return ResourceManager.GetString("lbID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dane identyfikacyjne.
        '''</summary>
        Friend Shared ReadOnly Property lbIdData() As String
            Get
                Return ResourceManager.GetString("lbIdData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Te dane są danymi podstawowymi jakie są wymagane 
        '''do prawidłowego druku rachunku
        '''
        '''Proszę wypełnić ten formularz..
        '''</summary>
        Friend Shared ReadOnly Property lbIdInfo() As String
            Get
                Return ResourceManager.GetString("lbIdInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import.
        '''</summary>
        Friend Shared ReadOnly Property lbImport() As String
            Get
                Return ResourceManager.GetString("lbImport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Importuj bazę.
        '''</summary>
        Friend Shared ReadOnly Property lbImportDB() As String
            Get
                Return ResourceManager.GetString("lbImportDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Błędna kategoria!.
        '''</summary>
        Friend Shared ReadOnly Property lbIncorrectCategory() As String
            Get
                Return ResourceManager.GetString("lbIncorrectCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Błędna jednostka!.
        '''</summary>
        Friend Shared ReadOnly Property lbIncorrectUnit() As String
            Get
                Return ResourceManager.GetString("lbIncorrectUnit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Informacje.
        '''</summary>
        Friend Shared ReadOnly Property lbInfo() As String
            Get
                Return ResourceManager.GetString("lbInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Z zakresu.
        '''</summary>
        Friend Shared ReadOnly Property lbInRange() As String
            Get
                Return ResourceManager.GetString("lbInRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Towar.
        '''</summary>
        Friend Shared ReadOnly Property lbItem() As String
            Get
                Return ResourceManager.GetString("lbItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Szczegóły towaru.
        '''</summary>
        Friend Shared ReadOnly Property lbItemDetails() As String
            Get
                Return ResourceManager.GetString("lbItemDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Towar jest już w bazie!.
        '''</summary>
        Friend Shared ReadOnly Property lbItemInDb() As String
            Get
                Return ResourceManager.GetString("lbItemInDb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nazwa.
        '''</summary>
        Friend Shared ReadOnly Property lbItemName() As String
            Get
                Return ResourceManager.GetString("lbItemName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Towary.
        '''</summary>
        Friend Shared ReadOnly Property lbItems() As String
            Get
                Return ResourceManager.GetString("lbItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Towarów w bazie: .
        '''</summary>
        Friend Shared ReadOnly Property lbItemsInDb() As String
            Get
                Return ResourceManager.GetString("lbItemsInDb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Język.
        '''</summary>
        Friend Shared ReadOnly Property lbLang() As String
            Get
                Return ResourceManager.GetString("lbLang", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to English.
        '''</summary>
        Friend Shared ReadOnly Property lbLangEN() As String
            Get
                Return ResourceManager.GetString("lbLangEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Polski.
        '''</summary>
        Friend Shared ReadOnly Property lbLangPL() As String
            Get
                Return ResourceManager.GetString("lbLangPL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Lewy.
        '''</summary>
        Friend Shared ReadOnly Property lbLeft() As String
            Get
                Return ResourceManager.GetString("lbLeft", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Główne.
        '''</summary>
        Friend Shared ReadOnly Property lbMainTab() As String
            Get
                Return ResourceManager.GetString("lbMainTab", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property lbMainTitle() As String
            Get
                Return ResourceManager.GetString("lbMainTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Miesięczny.
        '''</summary>
        Friend Shared ReadOnly Property lbMonthly() As String
            Get
                Return ResourceManager.GetString("lbMonthly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Imię.
        '''</summary>
        Friend Shared ReadOnly Property lbName() As String
            Get
                Return ResourceManager.GetString("lbName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nowy.
        '''</summary>
        Friend Shared ReadOnly Property lbNew() As String
            Get
                Return ResourceManager.GetString("lbNew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nowy rachunek.
        '''</summary>
        Friend Shared ReadOnly Property lbNewReceipt() As String
            Get
                Return ResourceManager.GetString("lbNewReceipt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dalej.
        '''</summary>
        Friend Shared ReadOnly Property lbNext() As String
            Get
                Return ResourceManager.GetString("lbNext", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nie.
        '''</summary>
        Friend Shared ReadOnly Property lbNo() As String
            Get
                Return ResourceManager.GetString("lbNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend Shared ReadOnly Property lbOk() As String
            Get
                Return ResourceManager.GetString("lbOk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Metoda płatności.
        '''</summary>
        Friend Shared ReadOnly Property lbPaymentMethod() As String
            Get
                Return ResourceManager.GetString("lbPaymentMethod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PESEL.
        '''</summary>
        Friend Shared ReadOnly Property lbPESEL() As String
            Get
                Return ResourceManager.GetString("lbPESEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telefon.
        '''</summary>
        Friend Shared ReadOnly Property lbPhone() As String
            Get
                Return ResourceManager.GetString("lbPhone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wybierz zakres.
        '''</summary>
        Friend Shared ReadOnly Property lbPickRange() As String
            Get
                Return ResourceManager.GetString("lbPickRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Kod pocztowy.
        '''</summary>
        Friend Shared ReadOnly Property lbPostal() As String
            Get
                Return ResourceManager.GetString("lbPostal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cena.
        '''</summary>
        Friend Shared ReadOnly Property lbPrice() As String
            Get
                Return ResourceManager.GetString("lbPrice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Drukuj.
        '''</summary>
        Friend Shared ReadOnly Property lbPrint() As String
            Get
                Return ResourceManager.GetString("lbPrint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Podgląd wydruku.
        '''</summary>
        Friend Shared ReadOnly Property lbPrintingWindow() As String
            Get
                Return ResourceManager.GetString("lbPrintingWindow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property lbProgramName() As String
            Get
                Return ResourceManager.GetString("lbProgramName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raporty.
        '''</summary>
        Friend Shared ReadOnly Property lbRaports() As String
            Get
                Return ResourceManager.GetString("lbRaports", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raporty okresowe.
        '''</summary>
        Friend Shared ReadOnly Property lbRaportsRange() As String
            Get
                Return ResourceManager.GetString("lbRaportsRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raporty z podziałem.
        '''</summary>
        Friend Shared ReadOnly Property lbRaportsVar() As String
            Get
                Return ResourceManager.GetString("lbRaportsVar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rachunek.
        '''</summary>
        Friend Shared ReadOnly Property lbReceipt() As String
            Get
                Return ResourceManager.GetString("lbReceipt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Faktura #.
        '''</summary>
        Friend Shared ReadOnly Property lbReceiptNO() As String
            Get
                Return ResourceManager.GetString("lbReceiptNO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rachunki.
        '''</summary>
        Friend Shared ReadOnly Property lbReceipts() As String
            Get
                Return ResourceManager.GetString("lbReceipts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Prawy.
        '''</summary>
        Friend Shared ReadOnly Property lbRight() As String
            Get
                Return ResourceManager.GetString("lbRight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zapisz.
        '''</summary>
        Friend Shared ReadOnly Property lbSave() As String
            Get
                Return ResourceManager.GetString("lbSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wybierz bazę.
        '''</summary>
        Friend Shared ReadOnly Property lbSelectDB() As String
            Get
                Return ResourceManager.GetString("lbSelectDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sprzedawca.
        '''</summary>
        Friend Shared ReadOnly Property lbSeller() As String
            Get
                Return ResourceManager.GetString("lbSeller", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Informacje o sprzedającym.
        '''</summary>
        Friend Shared ReadOnly Property lbSellerInfo() As String
            Get
                Return ResourceManager.GetString("lbSellerInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Usługa.
        '''</summary>
        Friend Shared ReadOnly Property lbService() As String
            Get
                Return ResourceManager.GetString("lbService", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ustaw bazę jako domyślną.
        '''</summary>
        Friend Shared ReadOnly Property lbSetDefaultDB() As String
            Get
                Return ResourceManager.GetString("lbSetDefaultDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ustawienia.
        '''</summary>
        Friend Shared ReadOnly Property lbSettings() As String
            Get
                Return ResourceManager.GetString("lbSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pokaż klientów.
        '''</summary>
        Friend Shared ReadOnly Property lbShowClients() As String
            Get
                Return ResourceManager.GetString("lbShowClients", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pokaż towary.
        '''</summary>
        Friend Shared ReadOnly Property lbShowItems() As String
            Get
                Return ResourceManager.GetString("lbShowItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pokaż rachunki.
        '''</summary>
        Friend Shared ReadOnly Property lbShowReceipts() As String
            Get
                Return ResourceManager.GetString("lbShowReceipts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Suma.
        '''</summary>
        Friend Shared ReadOnly Property lbSum() As String
            Get
                Return ResourceManager.GetString("lbSum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nazwisko.
        '''</summary>
        Friend Shared ReadOnly Property lbSurname() As String
            Get
                Return ResourceManager.GetString("lbSurname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Szablon.
        '''</summary>
        Friend Shared ReadOnly Property lbTemplate() As String
            Get
                Return ResourceManager.GetString("lbTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wyrównanie tekstu.
        '''</summary>
        Friend Shared ReadOnly Property lbTextAlign() As String
            Get
                Return ResourceManager.GetString("lbTextAlign", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Jednostka.
        '''</summary>
        Friend Shared ReadOnly Property lbUnit() As String
            Get
                Return ResourceManager.GetString("lbUnit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Uwaga.
        '''</summary>
        Friend Shared ReadOnly Property lbWarning() As String
            Get
                Return ResourceManager.GetString("lbWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zapraszamy!.
        '''</summary>
        Friend Shared ReadOnly Property lbWelcome() As String
            Get
                Return ResourceManager.GetString("lbWelcome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zanim zaczniemy pracę musimy uzupełnić klika ważnych
        '''		informacji. 
        '''To będzie szybie i łatwe!.
        '''</summary>
        Friend Shared ReadOnly Property lbWelcomeInfo() As String
            Get
                Return ResourceManager.GetString("lbWelcomeInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Możemy zaczynać!.
        '''</summary>
        Friend Shared ReadOnly Property lbWizardEnd() As String
            Get
                Return ResourceManager.GetString("lbWizardEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Super! Podstawowe dane mamy skonfigurowane.
        '''	Pamiętaj, że możesz te dane zmienić w każdej chwili w 
        '''	Ustawieniach.
        '''
        '''	Aby rozpocząć korzystanie z programu, naciśnij przycisk
        '''	&quot;Zakończ&quot;.
        '''
        '''		.
        '''</summary>
        Friend Shared ReadOnly Property lbWizardEnding() As String
            Get
                Return ResourceManager.GetString("lbWizardEnding", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chcesz zakończyć pracę kreatora?.
        '''</summary>
        Friend Shared ReadOnly Property lbWizardExit() As String
            Get
                Return ResourceManager.GetString("lbWizardExit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tak.
        '''</summary>
        Friend Shared ReadOnly Property lbYes() As String
            Get
                Return ResourceManager.GetString("lbYes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Plik konfiguracyjny aplikacji jest uszkodzony lub nie istnieje. Przeinstaluj aplikację..
        '''</summary>
        Friend Shared ReadOnly Property msgAppDatabaseHelper_configError() As String
            Get
                Return ResourceManager.GetString("msgAppDatabaseHelper.configError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nie można usunąć jednostki która jest przypisana do towaru!.
        '''</summary>
        Friend Shared ReadOnly Property msgCategoryDelError() As String
            Get
                Return ResourceManager.GetString("msgCategoryDelError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Baza utworzona pomyślnie!.
        '''</summary>
        Friend Shared ReadOnly Property msgDatabaseCreatedSuccess() As String
            Get
                Return ResourceManager.GetString("msgDatabaseCreatedSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Baza jest uszkodzona lub nieprawidłowa!.
        '''</summary>
        Friend Shared ReadOnly Property msgDatabaseError() As String
            Get
                Return ResourceManager.GetString("msgDatabaseError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Potwierdzenie.
        '''</summary>
        Friend Shared ReadOnly Property msgDatabaseHelper_confirmation() As String
            Get
                Return ResourceManager.GetString("msgDatabaseHelper.confirmation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nie można usunąć bazy która jest aktualnie w użyciu!.
        '''</summary>
        Friend Shared ReadOnly Property msgDatabaseInUseError() As String
            Get
                Return ResourceManager.GetString("msgDatabaseInUseError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Baza z tą nazwą już istnieje!.
        '''</summary>
        Friend Shared ReadOnly Property msgDatabaseNameExists() As String
            Get
                Return ResourceManager.GetString("msgDatabaseNameExists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edycja pomyślna!.
        '''</summary>
        Friend Shared ReadOnly Property msgEditOk() As String
            Get
                Return ResourceManager.GetString("msgEditOk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nie można wykonac operacji na pliku! Sprawdź czy masz wystaczające uprawnienia lub czy plik nie jest blokowany..
        '''</summary>
        Friend Shared ReadOnly Property msgFileError() As String
            Get
                Return ResourceManager.GetString("msgFileError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wystąpił problem podczas wykonywania operacji..
        '''</summary>
        Friend Shared ReadOnly Property msgGeneralError() As String
            Get
                Return ResourceManager.GetString("msgGeneralError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Niewystarczające dane.
        '''</summary>
        Friend Shared ReadOnly Property msgNnotEnoughData() As String
            Get
                Return ResourceManager.GetString("msgNnotEnoughData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nie wymagane.
        '''</summary>
        Friend Shared ReadOnly Property msgNotRequired() As String
            Get
                Return ResourceManager.GetString("msgNotRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Plik z bazą jest uszkodzony lub nieprawidłowy.
        '''</summary>
        Friend Shared ReadOnly Property msgSdfError() As String
            Get
                Return ResourceManager.GetString("msgSdfError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Czy chcesz usunąć .
        '''</summary>
        Friend Shared ReadOnly Property msgSureToDeleteX() As String
            Get
                Return ResourceManager.GetString("msgSureToDeleteX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Plik zip jest uszkodzony lub nieprawidłowy..
        '''</summary>
        Friend Shared ReadOnly Property msgZipError() As String
            Get
                Return ResourceManager.GetString("msgZipError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to System ewidencji sprzedaży.
        '''</summary>
        Friend Shared ReadOnly Property titleMain() As String
            Get
                Return ResourceManager.GetString("titleMain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sprzedaż.
        '''</summary>
        Friend Shared ReadOnly Property titleSales() As String
            Get
                Return ResourceManager.GetString("titleSales", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
