'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Language_en
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SalesInvoice.Language_en", GetType(Language_en).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Account number.
        '''</summary>
        Friend Shared ReadOnly Property lbAccountNO() As String
            Get
                Return ResourceManager.GetString("lbAccountNO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add.
        '''</summary>
        Friend Shared ReadOnly Property lbAdd() As String
            Get
                Return ResourceManager.GetString("lbAdd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add category.
        '''</summary>
        Friend Shared ReadOnly Property lbAddCategory() As String
            Get
                Return ResourceManager.GetString("lbAddCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add client.
        '''</summary>
        Friend Shared ReadOnly Property lbAddClient() As String
            Get
                Return ResourceManager.GetString("lbAddClient", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add item.
        '''</summary>
        Friend Shared ReadOnly Property lbAddItem() As String
            Get
                Return ResourceManager.GetString("lbAddItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Address.
        '''</summary>
        Friend Shared ReadOnly Property lbAddress() As String
            Get
                Return ResourceManager.GetString("lbAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Building no.
        '''</summary>
        Friend Shared ReadOnly Property lbAddressNo() As String
            Get
                Return ResourceManager.GetString("lbAddressNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add unit.
        '''</summary>
        Friend Shared ReadOnly Property lbAddUnits() As String
            Get
                Return ResourceManager.GetString("lbAddUnits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Amount.
        '''</summary>
        Friend Shared ReadOnly Property lbAmount() As String
            Get
                Return ResourceManager.GetString("lbAmount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apply.
        '''</summary>
        Friend Shared ReadOnly Property lbApply() As String
            Get
                Return ResourceManager.GetString("lbApply", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure?.
        '''</summary>
        Friend Shared ReadOnly Property lbAreYouSure() As String
            Get
                Return ResourceManager.GetString("lbAreYouSure", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Back.
        '''</summary>
        Friend Shared ReadOnly Property lbBack() As String
            Get
                Return ResourceManager.GetString("lbBack", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bank address.
        '''</summary>
        Friend Shared ReadOnly Property lbBankAddress() As String
            Get
                Return ResourceManager.GetString("lbBankAddress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bank details.
        '''</summary>
        Friend Shared ReadOnly Property lbBankDetails() As String
            Get
                Return ResourceManager.GetString("lbBankDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bank details.
        '''</summary>
        Friend Shared ReadOnly Property lbBankInfo() As String
            Get
                Return ResourceManager.GetString("lbBankInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Here are informations about bank accout, if you
        '''		will take payment via bank transfer, fill this form,
        '''		otherwise payment using bank transfer will be locked.
        '''
        '''You can change this info in Settings later..
        '''</summary>
        Friend Shared ReadOnly Property lbBankInfoWizard() As String
            Get
                Return ResourceManager.GetString("lbBankInfoWizard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bank transfer.
        '''</summary>
        Friend Shared ReadOnly Property lbBankTransfer() As String
            Get
                Return ResourceManager.GetString("lbBankTransfer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property lbCancel() As String
            Get
                Return ResourceManager.GetString("lbCancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This cannot be undone!.
        '''</summary>
        Friend Shared ReadOnly Property lbCannotUndone() As String
            Get
                Return ResourceManager.GetString("lbCannotUndone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cash.
        '''</summary>
        Friend Shared ReadOnly Property lbCash() As String
            Get
                Return ResourceManager.GetString("lbCash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Items categories.
        '''</summary>
        Friend Shared ReadOnly Property lbCategories() As String
            Get
                Return ResourceManager.GetString("lbCategories", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Category.
        '''</summary>
        Friend Shared ReadOnly Property lbCategory() As String
            Get
                Return ResourceManager.GetString("lbCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Center.
        '''</summary>
        Friend Shared ReadOnly Property lbCenter() As String
            Get
                Return ResourceManager.GetString("lbCenter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose.
        '''</summary>
        Friend Shared ReadOnly Property lbChoose() As String
            Get
                Return ResourceManager.GetString("lbChoose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose template.
        '''</summary>
        Friend Shared ReadOnly Property lbChooseTemplate() As String
            Get
                Return ResourceManager.GetString("lbChooseTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to City.
        '''</summary>
        Friend Shared ReadOnly Property lbCity() As String
            Get
                Return ResourceManager.GetString("lbCity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cleaning.
        '''</summary>
        Friend Shared ReadOnly Property lbCleaning() As String
            Get
                Return ResourceManager.GetString("lbCleaning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Client.
        '''</summary>
        Friend Shared ReadOnly Property lbClient() As String
            Get
                Return ResourceManager.GetString("lbClient", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Client details.
        '''</summary>
        Friend Shared ReadOnly Property lbClientDetails() As String
            Get
                Return ResourceManager.GetString("lbClientDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clients.
        '''</summary>
        Friend Shared ReadOnly Property lbClients() As String
            Get
                Return ResourceManager.GetString("lbClients", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close.
        '''</summary>
        Friend Shared ReadOnly Property lbClose() As String
            Get
                Return ResourceManager.GetString("lbClose", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Code.
        '''</summary>
        Friend Shared ReadOnly Property lbCode() As String
            Get
                Return ResourceManager.GetString("lbCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Value.
        '''</summary>
        Friend Shared ReadOnly Property lbCost() As String
            Get
                Return ResourceManager.GetString("lbCost", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Create.
        '''</summary>
        Friend Shared ReadOnly Property lbCreate() As String
            Get
                Return ResourceManager.GetString("lbCreate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Create database.
        '''</summary>
        Friend Shared ReadOnly Property lbCreateDB() As String
            Get
                Return ResourceManager.GetString("lbCreateDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Create task.
        '''</summary>
        Friend Shared ReadOnly Property lbCreateTask() As String
            Get
                Return ResourceManager.GetString("lbCreateTask", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database.
        '''</summary>
        Friend Shared ReadOnly Property lbDatabase() As String
            Get
                Return ResourceManager.GetString("lbDatabase", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Download data from CEIDG.
        '''</summary>
        Friend Shared ReadOnly Property lbDataFromCEIDG() As String
            Get
                Return ResourceManager.GetString("lbDataFromCEIDG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Date.
        '''</summary>
        Friend Shared ReadOnly Property lbDate() As String
            Get
                Return ResourceManager.GetString("lbDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Default.
        '''</summary>
        Friend Shared ReadOnly Property lbDefault() As String
            Get
                Return ResourceManager.GetString("lbDefault", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete.
        '''</summary>
        Friend Shared ReadOnly Property lbDelete() As String
            Get
                Return ResourceManager.GetString("lbDelete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete database.
        '''</summary>
        Friend Shared ReadOnly Property lbDeleteDB() As String
            Get
                Return ResourceManager.GetString("lbDeleteDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Document number.
        '''</summary>
        Friend Shared ReadOnly Property lbDocumentNo() As String
            Get
                Return ResourceManager.GetString("lbDocumentNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit.
        '''</summary>
        Friend Shared ReadOnly Property lbEdit() As String
            Get
                Return ResourceManager.GetString("lbEdit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit categories.
        '''</summary>
        Friend Shared ReadOnly Property lbEditCategories() As String
            Get
                Return ResourceManager.GetString("lbEditCategories", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit item category.
        '''</summary>
        Friend Shared ReadOnly Property lbEditCategory() As String
            Get
                Return ResourceManager.GetString("lbEditCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit units.
        '''</summary>
        Friend Shared ReadOnly Property lbEditUnits() As String
            Get
                Return ResourceManager.GetString("lbEditUnits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enable service.
        '''</summary>
        Friend Shared ReadOnly Property lbEnableScannerService() As String
            Get
                Return ResourceManager.GetString("lbEnableScannerService", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Finish.
        '''</summary>
        Friend Shared ReadOnly Property lbEnd() As String
            Get
                Return ResourceManager.GetString("lbEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fill all required fields!.
        '''</summary>
        Friend Shared ReadOnly Property lbEnterAllData() As String
            Get
                Return ResourceManager.GetString("lbEnterAllData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit.
        '''</summary>
        Friend Shared ReadOnly Property lbExit() As String
            Get
                Return ResourceManager.GetString("lbExit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export.
        '''</summary>
        Friend Shared ReadOnly Property lbExport() As String
            Get
                Return ResourceManager.GetString("lbExport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export database.
        '''</summary>
        Friend Shared ReadOnly Property lbExportDB() As String
            Get
                Return ResourceManager.GetString("lbExportDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extras.
        '''</summary>
        Friend Shared ReadOnly Property lbExtras() As String
            Get
                Return ResourceManager.GetString("lbExtras", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First run.
        '''</summary>
        Friend Shared ReadOnly Property lbFisrtRun() As String
            Get
                Return ResourceManager.GetString("lbFisrtRun", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Footer.
        '''</summary>
        Friend Shared ReadOnly Property lbFooterText() As String
            Get
                Return ResourceManager.GetString("lbFooterText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generate.
        '''</summary>
        Friend Shared ReadOnly Property lbGenerate() As String
            Get
                Return ResourceManager.GetString("lbGenerate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generating....
        '''</summary>
        Friend Shared ReadOnly Property lbGenerating() As String
            Get
                Return ResourceManager.GetString("lbGenerating", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Header text.
        '''</summary>
        Friend Shared ReadOnly Property lbHeaderText() As String
            Get
                Return ResourceManager.GetString("lbHeaderText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Header and footer info.
        '''</summary>
        Friend Shared ReadOnly Property lbHeadInfo() As String
            Get
                Return ResourceManager.GetString("lbHeadInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Header info
        '''(this info will be in upper left corner of receipt).
        '''</summary>
        Friend Shared ReadOnly Property lbHeadInfoWizard() As String
            Get
                Return ResourceManager.GetString("lbHeadInfoWizard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hi!.
        '''</summary>
        Friend Shared ReadOnly Property lbHi() As String
            Get
                Return ResourceManager.GetString("lbHi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ID.
        '''</summary>
        Friend Shared ReadOnly Property lbID() As String
            Get
                Return ResourceManager.GetString("lbID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Identification data.
        '''</summary>
        Friend Shared ReadOnly Property lbIdData() As String
            Get
                Return ResourceManager.GetString("lbIdData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This info is required for receipt to generate correctly.
        '''		Please fill this form.
        '''		.
        '''</summary>
        Friend Shared ReadOnly Property lbIdInfo() As String
            Get
                Return ResourceManager.GetString("lbIdInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import.
        '''</summary>
        Friend Shared ReadOnly Property lbImport() As String
            Get
                Return ResourceManager.GetString("lbImport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import database.
        '''</summary>
        Friend Shared ReadOnly Property lbImportDB() As String
            Get
                Return ResourceManager.GetString("lbImportDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid category!.
        '''</summary>
        Friend Shared ReadOnly Property lbIncorrectCategory() As String
            Get
                Return ResourceManager.GetString("lbIncorrectCategory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid unit!.
        '''</summary>
        Friend Shared ReadOnly Property lbIncorrectUnit() As String
            Get
                Return ResourceManager.GetString("lbIncorrectUnit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Informations.
        '''</summary>
        Friend Shared ReadOnly Property lbInfo() As String
            Get
                Return ResourceManager.GetString("lbInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to From range.
        '''</summary>
        Friend Shared ReadOnly Property lbInRange() As String
            Get
                Return ResourceManager.GetString("lbInRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item.
        '''</summary>
        Friend Shared ReadOnly Property lbItem() As String
            Get
                Return ResourceManager.GetString("lbItem", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Item details.
        '''</summary>
        Friend Shared ReadOnly Property lbItemDetails() As String
            Get
                Return ResourceManager.GetString("lbItemDetails", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This item is already in database!.
        '''</summary>
        Friend Shared ReadOnly Property lbItemInDb() As String
            Get
                Return ResourceManager.GetString("lbItemInDb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Friend Shared ReadOnly Property lbItemName() As String
            Get
                Return ResourceManager.GetString("lbItemName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Items.
        '''</summary>
        Friend Shared ReadOnly Property lbItems() As String
            Get
                Return ResourceManager.GetString("lbItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Items in database: .
        '''</summary>
        Friend Shared ReadOnly Property lbItemsInDb() As String
            Get
                Return ResourceManager.GetString("lbItemsInDb", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Language.
        '''</summary>
        Friend Shared ReadOnly Property lbLang() As String
            Get
                Return ResourceManager.GetString("lbLang", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to English.
        '''</summary>
        Friend Shared ReadOnly Property lbLangEN() As String
            Get
                Return ResourceManager.GetString("lbLangEN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Polski.
        '''</summary>
        Friend Shared ReadOnly Property lbLangPL() As String
            Get
                Return ResourceManager.GetString("lbLangPL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Left.
        '''</summary>
        Friend Shared ReadOnly Property lbLeft() As String
            Get
                Return ResourceManager.GetString("lbLeft", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Main.
        '''</summary>
        Friend Shared ReadOnly Property lbMainTab() As String
            Get
                Return ResourceManager.GetString("lbMainTab", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property lbMainTitle() As String
            Get
                Return ResourceManager.GetString("lbMainTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Monthly.
        '''</summary>
        Friend Shared ReadOnly Property lbMonthly() As String
            Get
                Return ResourceManager.GetString("lbMonthly", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Friend Shared ReadOnly Property lbName() As String
            Get
                Return ResourceManager.GetString("lbName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New.
        '''</summary>
        Friend Shared ReadOnly Property lbNew() As String
            Get
                Return ResourceManager.GetString("lbNew", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New receipt.
        '''</summary>
        Friend Shared ReadOnly Property lbNewReceipt() As String
            Get
                Return ResourceManager.GetString("lbNewReceipt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Next.
        '''</summary>
        Friend Shared ReadOnly Property lbNext() As String
            Get
                Return ResourceManager.GetString("lbNext", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No.
        '''</summary>
        Friend Shared ReadOnly Property lbNo() As String
            Get
                Return ResourceManager.GetString("lbNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend Shared ReadOnly Property lbOk() As String
            Get
                Return ResourceManager.GetString("lbOk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Payment method.
        '''</summary>
        Friend Shared ReadOnly Property lbPaymentMethod() As String
            Get
                Return ResourceManager.GetString("lbPaymentMethod", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to PESEL.
        '''</summary>
        Friend Shared ReadOnly Property lbPESEL() As String
            Get
                Return ResourceManager.GetString("lbPESEL", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telephone.
        '''</summary>
        Friend Shared ReadOnly Property lbPhone() As String
            Get
                Return ResourceManager.GetString("lbPhone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pick range.
        '''</summary>
        Friend Shared ReadOnly Property lbPickRange() As String
            Get
                Return ResourceManager.GetString("lbPickRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Postal code.
        '''</summary>
        Friend Shared ReadOnly Property lbPostal() As String
            Get
                Return ResourceManager.GetString("lbPostal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Price.
        '''</summary>
        Friend Shared ReadOnly Property lbPrice() As String
            Get
                Return ResourceManager.GetString("lbPrice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print.
        '''</summary>
        Friend Shared ReadOnly Property lbPrint() As String
            Get
                Return ResourceManager.GetString("lbPrint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Printing window.
        '''</summary>
        Friend Shared ReadOnly Property lbPrintingWindow() As String
            Get
                Return ResourceManager.GetString("lbPrintingWindow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend Shared ReadOnly Property lbProgramName() As String
            Get
                Return ResourceManager.GetString("lbProgramName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raports.
        '''</summary>
        Friend Shared ReadOnly Property lbRaports() As String
            Get
                Return ResourceManager.GetString("lbRaports", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ranged reports.
        '''</summary>
        Friend Shared ReadOnly Property lbRaportsRange() As String
            Get
                Return ResourceManager.GetString("lbRaportsRange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Splitted reports.
        '''</summary>
        Friend Shared ReadOnly Property lbRaportsVar() As String
            Get
                Return ResourceManager.GetString("lbRaportsVar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Receipt.
        '''</summary>
        Friend Shared ReadOnly Property lbReceipt() As String
            Get
                Return ResourceManager.GetString("lbReceipt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Receipt #.
        '''</summary>
        Friend Shared ReadOnly Property lbReceiptNO() As String
            Get
                Return ResourceManager.GetString("lbReceiptNO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Receipts.
        '''</summary>
        Friend Shared ReadOnly Property lbReceipts() As String
            Get
                Return ResourceManager.GetString("lbReceipts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Right.
        '''</summary>
        Friend Shared ReadOnly Property lbRight() As String
            Get
                Return ResourceManager.GetString("lbRight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Friend Shared ReadOnly Property lbSave() As String
            Get
                Return ResourceManager.GetString("lbSave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Choose databse.
        '''</summary>
        Friend Shared ReadOnly Property lbSelectDB() As String
            Get
                Return ResourceManager.GetString("lbSelectDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seller.
        '''</summary>
        Friend Shared ReadOnly Property lbSeller() As String
            Get
                Return ResourceManager.GetString("lbSeller", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Seller info.
        '''</summary>
        Friend Shared ReadOnly Property lbSellerInfo() As String
            Get
                Return ResourceManager.GetString("lbSellerInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Service.
        '''</summary>
        Friend Shared ReadOnly Property lbService() As String
            Get
                Return ResourceManager.GetString("lbService", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set database as default.
        '''</summary>
        Friend Shared ReadOnly Property lbSetDefaultDB() As String
            Get
                Return ResourceManager.GetString("lbSetDefaultDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Settings.
        '''</summary>
        Friend Shared ReadOnly Property lbSettings() As String
            Get
                Return ResourceManager.GetString("lbSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show clients.
        '''</summary>
        Friend Shared ReadOnly Property lbShowClients() As String
            Get
                Return ResourceManager.GetString("lbShowClients", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show items.
        '''</summary>
        Friend Shared ReadOnly Property lbShowItems() As String
            Get
                Return ResourceManager.GetString("lbShowItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Show receipts.
        '''</summary>
        Friend Shared ReadOnly Property lbShowReceipts() As String
            Get
                Return ResourceManager.GetString("lbShowReceipts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sum.
        '''</summary>
        Friend Shared ReadOnly Property lbSum() As String
            Get
                Return ResourceManager.GetString("lbSum", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Surname.
        '''</summary>
        Friend Shared ReadOnly Property lbSurname() As String
            Get
                Return ResourceManager.GetString("lbSurname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Template.
        '''</summary>
        Friend Shared ReadOnly Property lbTemplate() As String
            Get
                Return ResourceManager.GetString("lbTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Text align.
        '''</summary>
        Friend Shared ReadOnly Property lbTextAlign() As String
            Get
                Return ResourceManager.GetString("lbTextAlign", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unit.
        '''</summary>
        Friend Shared ReadOnly Property lbUnit() As String
            Get
                Return ResourceManager.GetString("lbUnit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning.
        '''</summary>
        Friend Shared ReadOnly Property lbWarning() As String
            Get
                Return ResourceManager.GetString("lbWarning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Welcome!.
        '''</summary>
        Friend Shared ReadOnly Property lbWelcome() As String
            Get
                Return ResourceManager.GetString("lbWelcome", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Before we start you have to fill some basic info.
        '''		It will be quick and easy!.
        '''</summary>
        Friend Shared ReadOnly Property lbWelcomeInfo() As String
            Get
                Return ResourceManager.GetString("lbWelcomeInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to We can start!.
        '''</summary>
        Friend Shared ReadOnly Property lbWizardEnd() As String
            Get
                Return ResourceManager.GetString("lbWizardEnd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Great! We have configured basic info.
        '''	Remember, you can change all of this info in Settings
        '''	later.
        '''
        '''	To start using program, press &quot;Finish&quot; button.
        '''
        '''		.
        '''</summary>
        Friend Shared ReadOnly Property lbWizardEnding() As String
            Get
                Return ResourceManager.GetString("lbWizardEnding", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to end this wizard?.
        '''</summary>
        Friend Shared ReadOnly Property lbWizardExit() As String
            Get
                Return ResourceManager.GetString("lbWizardExit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Yes.
        '''</summary>
        Friend Shared ReadOnly Property lbYes() As String
            Get
                Return ResourceManager.GetString("lbYes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Application config file is corrupted or not exists. Please reinstall program..
        '''</summary>
        Friend Shared ReadOnly Property msgAppconfigError() As String
            Get
                Return ResourceManager.GetString("msgAppconfigError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot delete unit that have items!.
        '''</summary>
        Friend Shared ReadOnly Property msgCategoryDelError() As String
            Get
                Return ResourceManager.GetString("msgCategoryDelError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to confirmation.
        '''</summary>
        Friend Shared ReadOnly Property msgconfirmation() As String
            Get
                Return ResourceManager.GetString("msgconfirmation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot create connection to database!.
        '''</summary>
        Friend Shared ReadOnly Property msgDatabaseConnectionError() As String
            Get
                Return ResourceManager.GetString("msgDatabaseConnectionError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database created successfully!.
        '''</summary>
        Friend Shared ReadOnly Property msgDatabaseCreatedSuccess() As String
            Get
                Return ResourceManager.GetString("msgDatabaseCreatedSuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database is corrupted or invalid!.
        '''</summary>
        Friend Shared ReadOnly Property msgDatabaseError() As String
            Get
                Return ResourceManager.GetString("msgDatabaseError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot delete database that is in use!.
        '''</summary>
        Friend Shared ReadOnly Property msgDatabaseInUseError() As String
            Get
                Return ResourceManager.GetString("msgDatabaseInUseError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database with that name already exists!.
        '''</summary>
        Friend Shared ReadOnly Property msgDatabaseNameExists() As String
            Get
                Return ResourceManager.GetString("msgDatabaseNameExists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Edit completed succesfully!.
        '''</summary>
        Friend Shared ReadOnly Property msgEditOk() As String
            Get
                Return ResourceManager.GetString("msgEditOk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot perform action on file! Check if you have permissions or if file is locked..
        '''</summary>
        Friend Shared ReadOnly Property msgFileError() As String
            Get
                Return ResourceManager.GetString("msgFileError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File with this name already exists. Please choose different name..
        '''</summary>
        Friend Shared ReadOnly Property msgFileExists() As String
            Get
                Return ResourceManager.GetString("msgFileExists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An error occured while performing operation.
        '''</summary>
        Friend Shared ReadOnly Property msgGeneralError() As String
            Get
                Return ResourceManager.GetString("msgGeneralError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not enough data, please fill all fields..
        '''</summary>
        Friend Shared ReadOnly Property msgNotEnoughData() As String
            Get
                Return ResourceManager.GetString("msgNotEnoughData", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not required.
        '''</summary>
        Friend Shared ReadOnly Property msgNotRequired() As String
            Get
                Return ResourceManager.GetString("msgNotRequired", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Database file is corrupted or invalid.
        '''</summary>
        Friend Shared ReadOnly Property msgSdfError() As String
            Get
                Return ResourceManager.GetString("msgSdfError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to delete  .
        '''</summary>
        Friend Shared ReadOnly Property msgSureToDeleteX() As String
            Get
                Return ResourceManager.GetString("msgSureToDeleteX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zip file is corrupted or invalid.
        '''</summary>
        Friend Shared ReadOnly Property msgZipError() As String
            Get
                Return ResourceManager.GetString("msgZipError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Records of the sales.
        '''</summary>
        Friend Shared ReadOnly Property titleMain() As String
            Get
                Return ResourceManager.GetString("titleMain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sales.
        '''</summary>
        Friend Shared ReadOnly Property titleSales() As String
            Get
                Return ResourceManager.GetString("titleSales", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
